# Generated by Django 5.0 on 2023-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_maqola'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
