# Generated by Django 5.0 on 2023-12-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_muallif_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='ism',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='muallif',
            name='yosh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
