# Generated by Django 5.0 on 2023-12-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_muallif_ism_alter_muallif_yosh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='ism',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='muallif',
            name='kasb',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='muallif',
            name='yosh',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
