# Generated by Django 5.0 on 2023-12-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_muallif_ism_alter_muallif_kasb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='muallif',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
